let numx = document.getElementById("num x");
let x = parseInt(prompt("Введите значение x"));
numx.innerHTML = x;
let numn = document.getElementById("numn");
let n = parseInt(prompt("Введите значение n"));
numn.innerHTML = n;
let res = document.getElementById("result");
let res = Math.pow(x, n);
result.innerHTML = res;
alert('Result of x = ' + x + ' in power of n = ' + n + ' equals ' + res);